---
language: python
python:
  - "3.6"
sudo: required
services:
  - docker
install:
  - pip install ansible==${ANSIBLE_VERSION}.* docker molecule
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
env:
  - ANSIBLE_VERSION=2.8
  - ANSIBLE_VERSION=2.9
