---
# file: roles/haproxy/tasks/main.yml
- include: install.yml
- include: firewall.yml
  when: haproxy_firewalld is defined and haproxy_firewalld == true
- include: selinux.yml
  when: haproxy_selinux is defined and haproxy_selinux == true
- include: config.yml
- include: sysctl.yml
